=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/dtd/LineItem.dtd
<?xml encoding="US-ASCII"?>

<!ELEMENT Order (Part+)>
<!ATTLIST Order key CDATA #REQUIRED>
<!ELEMENT Part (SuppKey,LineNumber,Quantity,ExtendedPrice,Discount,Tax,ReturnFlag,LineStatus,ShipDate,CommitDate,ReceiptDate,ShipInstruct,ShipMode,Comment)>
<!ELEMENT SuppKey (#PCDATA)>
<!ELEMENT LineNumber (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>
<!ELEMENT ExtendedPrice (#PCDATA)>
<!ELEMENT Discount (#PCDATA)>
<!ELEMENT Tax (#PCDATA)>
<!ELEMENT ReturnFlag (#PCDATA)>
<!ELEMENT LineStatus (#PCDATA)>
<!ELEMENT ShipDate (#PCDATA)>
<!ELEMENT CommitDate (#PCDATA)>
<!ELEMENT ReceiptDate (#PCDATA)>
<!ELEMENT ShipInstruct (#PCDATA)>
<!ELEMENT ShipMode (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>
<!ATTLIST Part key CDATA #REQUIRED>

=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/xml/litem1.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/LineItem.dtd">

<Order key="1">
  <Part key="156"> 
     <SuppKey>4</SuppKey>
     <LineNumber>1</LineNumber>
     <Quantity>17</Quantity>
     <ExtendedPrice>17954.55</ExtendedPrice>
     <Discount>0.04</Discount>
     <Tax>0.02</Tax>
     <ReturnFlag>N</ReturnFlag>
     <LineStatus>O</LineStatus>
     <ShipDate>1996-03-13</ShipDate>
     <CommitDate>1996-02-12</CommitDate>
     <ReceiptDate>1996-03-22</ReceiptDate>
     <ShipInstruct>DELIVER IN PERSON</ShipInstruct>
     <ShipMode>TRUCK</ShipMode>
     <Comment>iPBw4mMm7w7kQ zNPL i261OPP</Comment>
  </Part>
  <Part key="68"> 
     <SuppKey>9</SuppKey>
     <LineNumber>2</LineNumber>
     <Quantity>36</Quantity>
     <ExtendedPrice>34850.16</ExtendedPrice>
     <Discount>0.09</Discount>
     <Tax>0.06</Tax>
     <ReturnFlag>N</ReturnFlag>
     <LineStatus>O</LineStatus>
     <ShipDate>1996-04-12</ShipDate>
     <CommitDate>1996-02-28</CommitDate>
     <ReceiptDate>1996-04-20</ReceiptDate>
     <ShipInstruct>TAKE BACK RETURN</ShipInstruct>
     <ShipMode>MAIL</ShipMode>
     <Comment>5wM04SNyl0AnghCP2nx lAi</Comment>
  </Part>
  <Part key="64"> 
     <SuppKey>5</SuppKey>
     <LineNumber>3</LineNumber>
     <Quantity>8</Quantity>
     <ExtendedPrice>7712.48</ExtendedPrice>
     <Discount>0.10</Discount>
     <Tax>0.02</Tax>
     <ReturnFlag>N</ReturnFlag>
     <LineStatus>O</LineStatus>
     <ShipDate>1996-01-29</ShipDate>
     <CommitDate>1996-03-05</CommitDate>
     <ReceiptDate>1996-01-31</ReceiptDate>
     <ShipInstruct>TAKE BACK RETURN</ShipInstruct>
     <ShipMode>REG AIR</ShipMode>
     <Comment>SQC2C 5PNCy4mM</Comment>
  </Part>
  <Part key="3"> 
     <SuppKey>6</SuppKey>
     <LineNumber>4</LineNumber>
     <Quantity>28</Quantity>
     <ExtendedPrice>25284.00</ExtendedPrice>
     <Discount>0.09</Discount>
     <Tax>0.06</Tax>
     <ReturnFlag>N</ReturnFlag>
     <LineStatus>O</LineStatus>
     <ShipDate>1996-04-21</ShipDate>
     <CommitDate>1996-03-30</CommitDate>
     <ReceiptDate>1996-05-16</ReceiptDate>
     <ShipInstruct>NONE</ShipInstruct>
     <ShipMode>AIR</ShipMode>
     <Comment>Om0L65CSAwSj5k6k</Comment>
  </Part>
  <Part key="25"> 
     <SuppKey>8</SuppKey>
     <LineNumber>5</LineNumber>
     <Quantity>24</Quantity>
     <ExtendedPrice>22200.48</ExtendedPrice>
     <Discount>0.10</Discount>
     <Tax>0.04</Tax>
     <ReturnFlag>N</ReturnFlag>
     <LineStatus>O</LineStatus>
     <ShipDate>1996-03-30</ShipDate>
     <CommitDate>1996-03-14</CommitDate>
     <ReceiptDate>1996-04-01</ReceiptDate>
     <ShipInstruct>NONE</ShipInstruct>
     <ShipMode>FOB</ShipMode>
     <Comment>C2gOQj OB6RLk1BS15 igN</Comment>
  </Part>
  <Part key="16"> 
     <SuppKey>3</SuppKey>
     <LineNumber>6</LineNumber>
     <Quantity>32</Quantity>
     <ExtendedPrice>29312.32</ExtendedPrice>
     <Discount>0.07</Discount>
     <Tax>0.02</Tax>
     <ReturnFlag>N</ReturnFlag>
     <LineStatus>O</LineStatus>
     <ShipDate>1996-01-30</ShipDate>
     <CommitDate>1996-02-07</CommitDate>
     <ReceiptDate>1996-02-03</ReceiptDate>
     <ShipInstruct>DELIVER IN PERSON</ShipInstruct>
     <ShipMode>MAIL</ShipMode>
     <Comment>CB0SnyOL PQ32B70wB75k 6Aw10m0wh</Comment>
  </Part>
</Order>

=== alandohf/poonzref/refs/db2/samples/extenders/db2xml/xml/litem3.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/LineItem.dtd">

<Order key="3">
  <Part key="107"> 
     <SuppKey>2</SuppKey>
     <LineNumber>1</LineNumber>
     <Quantity>38</Quantity>
     <ExtendedPrice>38269.80</ExtendedPrice>
     <Discount>0.00</Discount>
     <Tax>0.05</Tax>
     <ReturnFlag>A</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1993-12-11</ShipDate>
     <CommitDate>1993-11-27</CommitDate>
     <ReceiptDate>1993-12-16</ReceiptDate>
     <ShipInstruct>TAKE BACK RETURN</ShipInstruct>
     <ShipMode>RAIL</ShipMode>
     <Comment>3AR yMS77lQ12kR</Comment>
  </Part>
  <Part key="195"> 
     <SuppKey>7</SuppKey>
     <LineNumber>2</LineNumber>
     <Quantity>30</Quantity>
     <ExtendedPrice>32855.70</ExtendedPrice>
     <Discount>0.05</Discount>
     <Tax>0.01</Tax>
     <ReturnFlag>A</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1994-02-05</ShipDate>
     <CommitDate>1993-12-29</CommitDate>
     <ReceiptDate>1994-02-18</ReceiptDate>
     <ShipInstruct>TAKE BACK RETURN</ShipInstruct>
     <ShipMode>FOB</ShipMode>
     <Comment>6wQnO0Llg6y</Comment>
  </Part>
  <Part key="101"> 
     <SuppKey>2</SuppKey>
     <LineNumber>3</LineNumber>
     <Quantity>44</Quantity>
     <ExtendedPrice>44048.40</ExtendedPrice>
     <Discount>0.07</Discount>
     <Tax>0.03</Tax>
     <ReturnFlag>R</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1994-01-19</ShipDate>
     <CommitDate>1993-12-23</CommitDate>
     <ReceiptDate>1994-02-15</ReceiptDate>
     <ShipInstruct>TAKE BACK RETURN</ShipInstruct>
     <ShipMode>SHIP</ShipMode>
     <Comment>LhiA7wygz0k4g4zRhMLBAM</Comment>
  </Part>
  <Part key="46"> 
     <SuppKey>9</SuppKey>
     <LineNumber>4</LineNumber>
     <Quantity>37</Quantity>
     <ExtendedPrice>35003.48</ExtendedPrice>
     <Discount>0.09</Discount>
     <Tax>0.05</Tax>
     <ReturnFlag>A</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1993-12-22</ShipDate>
     <CommitDate>1993-12-28</CommitDate>
     <ReceiptDate>1994-01-04</ReceiptDate>
     <ShipInstruct>DELIVER IN PERSON</ShipInstruct>
     <ShipMode>AIR</ShipMode>
     <Comment>jykM7l5S7xl6nin26jhn75C60kj2iQAgg</Comment>
  </Part>
  <Part key="5"> 
     <SuppKey>2</SuppKey>
     <LineNumber>5</LineNumber>
     <Quantity>6</Quantity>
     <ExtendedPrice>5430.00</ExtendedPrice>
     <Discount>0.04</Discount>
     <Tax>0.01</Tax>
     <ReturnFlag>R</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1994-01-28</ShipDate>
     <CommitDate>1993-12-15</CommitDate>
     <ReceiptDate>1994-02-14</ReceiptDate>
     <ShipInstruct>TAKE BACK RETURN</ShipInstruct>
     <ShipMode>REG AIR</ShipMode>
     <Comment>6nmBmjQkgiCyzCQBkxPPOx5j4hB 0lRywgniP7</Comment>
  </Part>
  <Part key="196"> 
     <SuppKey>8</SuppKey>
     <LineNumber>6</LineNumber>
     <Quantity>35</Quantity>
     <ExtendedPrice>38366.65</ExtendedPrice>
     <Discount>0.01</Discount>
     <Tax>0.05</Tax>
     <ReturnFlag>R</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1993-12-23</ShipDate>
     <CommitDate>1994-01-10</CommitDate>
     <ReceiptDate>1994-01-13</ReceiptDate>
     <ShipInstruct>COLLECT COD</ShipInstruct>
     <ShipMode>RAIL</ShipMode>
     <Comment>nNMwmwnnji74jRnMPl0z41BgwCLjk7ANPQM</Comment>
  </Part>
</Order>

=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/xml/litem2.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/LineItem.dtd">

<Order key="2">
  <Part key="169"> 
     <SuppKey>10</SuppKey>
     <LineNumber>1</LineNumber>
     <Quantity>24</Quantity>
     <ExtendedPrice>25659.84</ExtendedPrice>
     <Discount>0.00</Discount>
     <Tax>0.08</Tax>
     <ReturnFlag>N</ReturnFlag>
     <LineStatus>O</LineStatus>
     <ShipDate>1997-03-05</ShipDate>
     <CommitDate>1997-02-09</CommitDate>
     <ReceiptDate>1997-03-11</ReceiptDate>
     <ShipInstruct>COLLECT COD</ShipInstruct>
     <ShipMode>AIR</ShipMode>
     <Comment>O52M70MRgRNnmm476mNm</Comment>
  </Part>
</Order>

=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/xml/litem5.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/LineItem.dtd">

<Order key="5">
  <Part key="5"> 
     <SuppKey>2</SuppKey>
     <LineNumber>1</LineNumber>
     <Quantity>45</Quantity>
     <ExtendedPrice>40725.00</ExtendedPrice>
     <Discount>0.06</Discount>
     <Tax>0.00</Tax>
     <ReturnFlag>R</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1994-11-18</ShipDate>
     <CommitDate>1994-10-20</CommitDate>
     <ReceiptDate>1994-12-09</ReceiptDate>
     <ShipInstruct>NONE</ShipInstruct>
     <ShipMode>AIR</ShipMode>
     <Comment>MQR1NNRmlBx1ylCy3k7lBS0 </Comment>
  </Part>
  <Part key="20"> 
     <SuppKey>10</SuppKey>
     <LineNumber>2</LineNumber>
     <Quantity>49</Quantity>
     <ExtendedPrice>45080.98</ExtendedPrice>
     <Discount>0.10</Discount>
     <Tax>0.00</Tax>
     <ReturnFlag>A</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1994-08-25</ShipDate>
     <CommitDate>1994-10-05</CommitDate>
     <ReceiptDate>1994-09-09</ReceiptDate>
     <ShipInstruct>TAKE BACK RETURN</ShipInstruct>
     <ShipMode>RAIL</ShipMode>
     <Comment>kAPQM67LOxSNlnimlM</Comment>
  </Part>
  <Part key="129"> 
     <SuppKey>8</SuppKey>
     <LineNumber>3</LineNumber>
     <Quantity>27</Quantity>
     <ExtendedPrice>27786.24</ExtendedPrice>
     <Discount>0.06</Discount>
     <Tax>0.07</Tax>
     <ReturnFlag>R</ReturnFlag>
     <LineStatus>F</LineStatus>
     <ShipDate>1994-11-01</ShipDate>
     <CommitDate>1994-09-07</CommitDate>
     <ReceiptDate>1994-11-08</ReceiptDate>
     <ShipInstruct>DELIVER IN PERSON</ShipInstruct>
     <ShipMode>SHIP</ShipMode>
     <Comment>CxQnkxC3xP zyiRBzj6wB30NnCi hx Q4y1OQ kg6P</Comment>
  </Part>
</Order>
