=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/dtd/Order.dtd
<?xml encoding="US-ASCII"?>

<!ELEMENT Order (Customer, Status, TotalPrice, Date, Priority, Clerk, ShipPriority, Comment)>
<!ATTLIST Order key CDATA #REQUIRED>
<!ELEMENT Customer (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT TotalPrice (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Priority (#PCDATA)>
<!ELEMENT Clerk (#PCDATA)>
<!ELEMENT ShipPriority (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>

=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/xml/order4.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/Order.dtd">

<Order key="4">
     <Customer>137</Customer>
     <Status>O</Status>
     <TotalPrice>4567.44</TotalPrice>
     <Date>1995-10-11</Date>
     <Priority>5-LOW</Priority>
     <Clerk>Clerk#000000124</Clerk>
     <ShipPriority>0</ShipPriority>
     <Comment>CP42CySQlz64n3mCyjm17 4B0CL L5772m4k2Ai4h1nPySwSmNyCl4jOAOx5y4Rjx36nhO1x2x4Qw</Comment>
</Order>

=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/xml/order2.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/Order.dtd">

<Order key="2">
     <Customer>79</Customer>
     <Status>O</Status>
     <TotalPrice>27712.62</TotalPrice>
     <Date>1996-12-01</Date>
     <Priority>1-URGENT</Priority>
     <Clerk>Clerk#000000880</Clerk>
     <ShipPriority>0</ShipPriority>
     <Comment>5PRxL1nM7xhQNzP2hnjhy1zz ykhg4P2A MMg5Px3OCN 0B0iyCRgiC2</Comment>
</Order>

=== alandohf/poonzref/trunk/refs/db2/samples/extenders/db2xml/xml/order5.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/Order.dtd">

<Order key="5">
     <Customer>56</Customer>
     <Status>F</Status>
     <TotalPrice>106801.77</TotalPrice>
     <Date>1994-07-30</Date>
     <Priority>5-LOW</Priority>
     <Clerk>Clerk#000000925</Clerk>
     <ShipPriority>0</ShipPriority>
     <Comment>3PNC7zMP534MSizgy34Bxj62l0C7n6PBk7</Comment>
</Order>

=== alandohf/poonzref/refs/db2/samples/extenders/db2xml/xml/invalid1.xml
<?xml version="1.0"?>
<!DOCTYPE Order SYSTEM "/opt/IBM/db2/V9.1/samples/extenders/db2xml/dtd/Order.dtd">

<Order key="101">
     <Customer>1111</Customer>
     <Status>O</Status>
     <TotalPrice>131251.81</TotalPrice>
     <invalid>*** bogus ***</invalid>
     <Date>1996-01-02</Date>
     <Priority>5-LOW</Priority>
     <Clerk>Clerk#000000951</Clerk>
     <ShipPriority>0</ShipPriority>
     <Comment>A0xCm5ARNL mxjChn2kC64xA4L6zBg2O5jhg M42izyPO  QlymN1ky5kmSiSgBAQA</Comment>
</Order>
